# Complex Simulation Analysis

## Initial
```{r}

hist(y1_end_cap)
hist(y2_end_cap)
hist(y3_end_cap)
hist(y4_end_cap)
ggplot() + geom_histogram(aes(y5_end_cap), bins = 200) + geom_vline(xintercept = 2e6)

ggplot() + geom_histogram(aes(cap_y4_s5), bins = 200)

discovered

ggplot() + geom_histogram(aes(discovered), bins = 200)


plot(ecdf(y5_end_cap))

quantile(ecdf(y5_end_cap), 0.99, type = 7)

table(everbankrupt)
table(discovered)

t <- discovered
t[t > 1] <- 2
table(t)

table(lost_mine)

breakbust <- rep(1, num_sim)
breakbust[y5_end_cap < 0] <- 0

table(breakbust)

```

```{r}
ggplot() + geom_histogram(aes(y5_end_cap), bins = 200) + geom_vline(xintercept = 2e6)
```


```{r}
#resultstest <- data.frame(all0.5noplex = y5_end_cap)

#resultstest$all0.95_noplex <- y5_end_cap

#resultstest$all0.05_noplex <- y5_end_cap

#resultstest$highdisco_noplex <- y5_end_cap

#resultstest$highresol_noplex <- y5_end_cap

#saveRDS(resultstest, "./intialtweak.RDS")
  

resultslong <- resultstest %>% 
  pivot_longer(cols = 1:ncol(resultstest), names_to = "run", values_to = "outcome")

ggplot(resultslong, aes(x = outcome, fill = run)) + geom_histogram(bins = 200, position="identity", alpha = 0.5) + geom_vline(xintercept = 2e6)
```


```{r}

quantile(ecdf(resultstest$all0.5noplex), c(0.02, 0.1, 0.5, 0.9, 0.95, 0.999), type = 7)
quantile(ecdf(resultstest$all0.95_noplex), c(0.02, 0.1, 0.5, 0.9, 0.95, 0.999), type = 7) 
quantile(ecdf(resultstest$all0.05_noplex), c(0.02, 0.1, 0.5, 0.9, 0.95, 0.999), type = 7) 
quantile(ecdf(resultstest$highdisco_noplex), c(0.02, 0.1, 0.5, 0.9, 0.95, 0.999), type = 7)
quantile(ecdf(resultstest$highresol_noplex), c(0.02, 0.1, 0.5, 0.9, 0.95, 0.999), type = 7) 

```

### output collated

```{r}

names(outputy1)[2:ncol(outputy1)] <- paste("y1",names(outputy1)[2:ncol(outputy1)], sep = ".")
names(outputy2)[2:ncol(outputy2)] <- paste("y2",names(outputy2)[2:ncol(outputy2)], sep = ".")
names(outputy3)[2:ncol(outputy3)] <- paste("y3",names(outputy3)[2:ncol(outputy3)], sep = ".")
names(outputy4)[2:ncol(outputy4)] <- paste("y4",names(outputy4)[2:ncol(outputy4)], sep = ".")
names(outputy5)[2:ncol(outputy5)] <- paste("y5",names(outputy5)[2:ncol(outputy5)], sep = ".")

output <- data.frame(runid = 1:num_sim)

output <- output %>% 
  left_join(outputy1, by = "runid") %>% 
  left_join(outputy2, by = "runid") %>% 
  left_join(outputy3, by = "runid") %>% 
  left_join(outputy4, by = "runid") %>% 
  left_join(outputy5, by = "runid")


ggplot(output, aes(x = y5.end_cap)) + geom_histogram(bins = 100)

highout <- output %>% 
  filter(y5.end_cap >= 2.5e7) %>% 
  arrange(desc(y5.end_cap))

```

